apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-lightblue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: pod-webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: __IMAGE__
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lightblue-service
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
   - protocol: TCP
     port: 8000
     nodePort: 30130
