apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: bluecompute-web-pr-003
spec:
  pipelineRef:
    name: bluecompute-build-and-deploy-pipeline-web
  resources:
    - name: git-source-web
      resourceRef:
        name: git-source-web
    - name: docker-image-web
      resourceRef:
        name: docker-image-web
  params:
    - name: pathToYamlFile
      value: "k8s_yamls"
    - name: pathToDeployablesFile
      value: "k8s_yamls_mcm"
  serviceAccountName: pipeline
  timeout: "1h0m0s"
